name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config supercollider-dev

    - name: Configure Project
      run: chmod +x configure && ./configure

    - name: Compile
      run: make

    - name: Verify Build Output
      run: test -f XYScope.so
